name: create release artifact
on: workflow_dispatch

jobs:
  create_rpm:
    name: create rpm from repo
    runs-on: self-hosted
    
    permissions:
      contents: read
      security-events: write
      actions: read

    steps:
      - uses: actions/checkout@v7

      - name: trivy vulnerability scan
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: 'fs'
          scan-ref: '.'
          vuln-type: 'library'
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: put in security tab
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: 'trivy-results.sarif'

      - name: create source archive
        run: |
          export VERSION=$(grep ^Version: lmslogger.spec | sed -e 's/Version: //')
          git archive --verbose --format=tgz \
          --prefix="lmslogger-${VERSION}/" \
          --output ${{ vars.PKG_NAME }}-${{ github.ref_name }}.tgz HEAD .

      - name: build rpm
        run: |
          export RUNDIR=${PWD}
          export VERSION=$(grep ^Version: lmslogger.spec | sed -e 's/Version: //')
          rpmdev-setuptree
          cd ~/rpmbuild
          cp ${RUNDIR}/lmslogger-main.tgz SOURCES/lmslogger-${VERSION}.tgz
          cp ${RUNDIR}/lmslogger.spec SPECS/
          rpmbuild -ba SPECS/lmslogger.spec

      - name: Push rpm to ghcr
        uses: macbre/push-to-ghcr@master
        with:
          image_name: ${{ vars.PKG_NAME }}-${{ github.ref_name}}.${{ vars.ARCH }}.rpm
          github_token: ${{ secrets.GHCR_TOKEN }}

      # - name: Upload rpm as artifact
      #   uses: actions/upload-artifact@v7
      #   with:
      #     name: ${{ vars.PKG_NAME }}-${{ github.ref_name}}.${{ vars.ARCH }}.rpm
      #     path: ~/rpmbuild/RPMS/${{ vars.ARCH }}/*.rpm

      - name: clean up
        run: |
          rm -rf ~/rpmbuild
          rm -rf ./* || true
          rm -rf ./.??* || true
