name: create release artifact
on: workflow_dispatch

jobs:
  create_rpm:
    name: create rpm from repo
    runs-on: self-hosted
    
    steps:
      - uses: actions/checkout@v7

      - name: create source archive
        run: |
          export VERSION=$(grep ^Version: lmslogger.spec | sed -e 's/Version: //')
          git archive --verbose --format=tgz \
          --prefix="lmslogger-${VERSION}/" \
          --output ${{ vars.PKG_NAME }}-${{ github.ref_name }}.tgz HEAD .

      - name: build rpm
        run: |
          export RUNDIR=${PWD}
          export VERSION=$(grep ^Version: lmslogger.spec | sed -e 's/Version: //')
          rpmdev-setuptree
          cd ~/rpmbuild
          cp ${RUNDIR}/lmslogger-main.tgz SOURCES/lmslogger-${VERSION}.tgz
          cp ${RUNDIR}/lmslogger.spec SPECS/
          rpmbuild -ba SPECS/lmslogger.spec

      - name: Upload rpm as artifact
        uses: actions/upload-artifact@v7
        with:
          name: ${{ vars.PKG_NAME }}-${{ github.ref_name}}.${{ vars.ARCH }}.rpm
          path: ~/rpmbuild/RPMS/${{ vars.ARCH }}/*.rpm

      - name: clean up
        run: |
          rm -rf ~/rpmbuild
