name: create release artifact
on: workflow_dispatch

jobs:
  create_rpm:
    name: create rpm from repo
    runs-on: self-hosted
    
    permissions:
      contents: write
      security-events: write
      actions: read

    steps:
      - uses: actions/checkout@v7

      - name: bump version and tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GHCR_TOKEN }}
          create_annotated_tag: true

      - name: debug tag_version outputs
        run: |
          printf 'github.ref_name=%s\n' '${{ github.ref_name }}'
          printf 'tag=%s\n' '${{ steps.tag_version.outputs.tag }}'
          printf 'version=%s\n' '${{ steps.tag_version.outputs.version }}'
          printf 'github_tag=%s\n' '${{ steps.tag_version.outputs.github_tag }}'
          printf 'ref=%s\n' '${{ steps.tag_version.outputs.ref }}'

      - name: trivy vulnerability scan
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: 'fs'
          scan-ref: '.'
          vuln-type: 'library'
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: put in security tab
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: 'trivy-results.sarif'

      - name: create source archive
        run: |
          export VERSION=$(grep ^Version: lmslogger.spec | sed -e 's/Version: //')
          git archive --verbose --format=tgz \
          --prefix="lmslogger-${VERSION}/" \
          --output ${{ vars.PKG_NAME }}-${{ github.ref_name }}.tgz HEAD .

      - name: build rpm
        run: |
          export RUNDIR=${PWD}
          export VERSION=$(grep ^Version: lmslogger.spec | sed -e 's/Version: //')
          rpmdev-setuptree
          cd ~/rpmbuild
          cp ${RUNDIR}/lmslogger-main.tgz SOURCES/lmslogger-${VERSION}.tgz
          cp ${RUNDIR}/lmslogger.spec SPECS/
          rpmbuild -ba SPECS/lmslogger.spec

      - name: upload release asset
        uses: softprops/action-gh-release@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GHCR_TOKEN }}
        with:
          tag_name: ${{ steps.tag_version.outputs.tag }}
          files: ~/rpmbuild/RPMS/${{ vars.ARCH }}/*.rpm
            

      # - name: upload release asset
      #   id: upload-release-asset
      #   uses: action/upload-release-asset@v1
      #   env:
      #     GITHUB_TOKEN ${{ secrets.GHCR_TOKEN }}
      #   with:
      #     asset_paths: '[ "~/rpmbuild/RPMS/${{ vars.ARCH }}/*.rpm" ]'

      - name: clean up
        run: |
          rm -rf ~/rpmbuild
          rm -rf ./* || true
          rm -rf ./.??* || true
